RF: relocate pytest import
import pyfilesec was failing in PsychoPy StandAlone 1.79.00 due to a pytest
dependency (config). But only need pytest in tests, so relocate it.

    import pyfilesec
  File "/Applications/PsychoPy2.app/Contents/Resources/lib/python2.7/pyfilesec/__init__.py", line 46, in <module>
    import pytest
  File "pytest.pyc", line 13, in <module>
  File "_pytest/core.pyc", line 442, in _preloadplugins
  File "_pytest/core.pyc", line 79, in __init__
  File "_pytest/core.pyc", line 196, in import_plugin
  File "_pytest/core.pyc", line 331, in importplugin
ImportError: No module named config